version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "clickup-automation"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-o4qqfql5vxkx"
s3_prefix = "clickup-automation"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
