AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  clickup-automation

  Sample SAM Template for clickup-automation

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    Tracing: Active
  Api:
    TracingEnabled: True

Resources:
  ClickupDailyFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: clickup_daily/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
       - x86_64
#      Environment:
#        Variables:
#          CLICKUP_KEY: '{{resolve:secretsmanager:arn:aws:eu-west-1:544005128464:secret:ClickupDailyFunction-i7pUNo:SecretString:CLICKUP_KEY}}'
#          DISCORD_WEBHOOK: '{{resolve:secretsmanager:arn:aws:eu-west-1:544005128464:secret:ClickupDailyFunction-i7pUNo:SecretString:DISCORD_WEBHOOK}}'
      Events:
        Manual:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /daily
            Method: get
        Timer:
          Type: Schedule
          Properties:
            Schedule: cron(30 2 * * ? *)
            Name: daily-schedule
            Description: Daily schedule
            Enabled: True
  DiscordInteractionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: clickup_daily/
      Handler: app.interactions
      Runtime: python3.9
      Architectures:
       - x86_64
      Events:
        Manual:
          Type: Api
          Properties:
            Path: /interactions
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ClickupDailyApi:
    Description: "API Gateway endpoint URL for Prod stage for ClickUp Daily function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/daily/"
  DiscordInteractionsApi:
    Description: "API Gateway endpoint URL for Prod stage for Discord Interations function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/interactions/"
  ClickupDailyFunction:
    Description: "ClickupDaily Lambda Function ARN"
    Value: !GetAtt ClickupDailyFunction.Arn
  DiscordInteractionsFunction:
    Description: "Discord Interactions Lambda Function ARN"
    Value: !GetAtt DiscordInteractionsFunction.Arn
  ClickupDailyIamRole:
    Description: "Implicit IAM Role created for Clickup Daily function"
    Value: !GetAtt ClickupDailyFunctionRole.Arn
